name: Check

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Test
        run: |
          pip install pytest
          pytest
      - name: Lint
        run: |
          flake8 --jobs 4 --statistics --show-source source tests
	        mypy source
	        black --target-version py36 --skip-string-normalization --line-length=119 --check source tests
